name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -s http://localhost:4444/status | grep -q 'ready' || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Wait for Selenium to be ready
        
        run: |
          echo "⏳ Waiting for Selenium Hub on localhost:4444/status ..."
          for i in {1..20}; do
            if curl -s http://localhost:4444/status | grep -q '"ready":true'; then
              echo "✅ Selenium Hub is ready"
              exit 0
            fi
            echo "  still not ready, retrying..."
            sleep 3
          done
          echo "❌ Selenium Hub failed to start in time"
          exit 1

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test --info

      - name: Archive test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/index.html
