name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
       
        options: >-
          --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep -q '\"ready\":true'" 
          --health-interval=5s 
          --health-timeout=2s 
          --health-retries=10

    steps:
      - uses: actions/checkout@v3

     
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Wait for Selenium to be ready
       
        run: |
          for i in {1..10}; do
            curl -s http://localhost:4444/wd/hub/status | grep '"ready":true' && break
            echo "Waiting for selenium..." && sleep 3
          done

      - name: Build & test with Gradle
       
        run: ./gradlew clean test
