name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -f http://localhost:4444/status || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Wait for Selenium Hub
        run: |
          echo "Waiting for Selenium Hub..."
          until curl -s http://localhost:4444/status | grep '"ready":true'; do
            sleep 1
          done
          echo "Selenium Hub is ready."

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build & test with Gradle
        run: ./gradlew clean test --info --no-daemon
